### ISSUE TITLE
issues while converting gregorian to jalali

### ISSUE THREAD

**Issue by Sepehr79** [eloyzone/jalali-calendar#2]
![Screenshot (128)](https://user-images.githubusercontent.com/68536625/112744425-3ff7f780-8fb5-11eb-949b-3028e28f0a29.png)

**Comment by eloyzone** [comment]
I am sorry my response is late,

Yes this issue happened because you are using the same DateConverter instance twice. First you used jalaliToGregorian and then gregorianToJalali.

A simple work-around is to create a new instance once you want to convert another date.

        DateConverter dateConverter1 = new DateConverter();
        LocalDate  localDate = dateConverter1.jalaliToGregorian(1400,1,8);

        DateConverter dateConverter2 = new DateConverter();
        JalaliDate jalaliDate = dateConverter2.gregorianToJalali(2021,3,28);

I know it seems ridiculous, but currently I am out of time and I hope to fix this issue in the near future.
